name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: asrma7/quirky-nanotube-jackalope/dev
          work-dir: .
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ca-central-1

